unique_ids:
  assets:
    standard-page.html: KQCIFO5Y2IZVJ5CA2IH4L6QKU6HRALT2
    theme.css: QUKXO265ZUIM5XAYA43H4DDNA57RI4EL
  forms:
    Form1: GYSBGM3FNQHURMT73MWXHKTLBWCT6V3Q
  modules: {}
  scripts: {}
  server_modules: {}
